import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";
import React from "react";
import I18nProvider from "@/components/I18nProvider"; // Import du Provider

export const metadata: Metadata = {
  title: "Title",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <I18nProvider>
          <Navbar />
          {children}
        </I18nProvider>
      </body>
    </html>
  );
}
